server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  application:
    name: weiss-data
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

