logging:
  level:
    org.springframework: ERROR
    com.weiss.weissdata: INFO
  file: weis-data.log
server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  application:
    name: weiss-data
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
limitOfFeed: 20
